Repository cohere-ai/sandbox-conversant-lib, pull requests merged in 2022-11, with the labels that each got.

#42 fix: replace streamlit-chat with streamlit-talk
  app/ui.py
  poetry.lock
  pyproject.toml
Labels: bug

#41 docs: enhance explanations and code examples on README
  .github/workflows/run_tests.yaml
  README.md
  app/utils.py
  poetry.lock
  static/fortune-teller-edit.png
  static/fortune-teller-setup.png
Labels: documentation

#46 fix: encode chatbot without cohere client, decode with client
  app/streamlit_example.py
  app/utils.py
  conversant/utils/demo_utils.py
  tests/utils/test_demo_utils.py
Labels: bug

#47 docs: README grammar, PyPI link and shield, get support
  README.md
Labels: documentation

#44 docs: Add PyPI metadata when using `poetry publish`
  CHANGELOG.md
  pyproject.toml
Labels: documentation

#52 docs: add sandbox announcement and remove launch_streamlit example
  README.md
Labels: documentation

#51 fix: move streamlit demo into conversant
  README.md
  conversant/demo/__init__.py
  conversant/demo/streamlit_example.py
  conversant/demo/styles.css
  conversant/demo/ui.py
  conversant/demo/utils.py
  conversant/prompt_chatbot.py
  conversant/utils/demo_utils.py
Labels: bug

#56 docs: update demo link
  README.md
Labels: bug, documentation

#57 fix: update prefix in persona selection
  conversant/demo/streamlit_example.py
Labels: clean up

#61 add css styling to resolve top/bottom chat issue
  conversant/demo/streamlit_example.py
  conversant/demo/styles.css
Labels: enhancement

#63 fix: update poetry version in CONTRIBUTORS.md
  CONTRIBUTORS.md
  poetry.lock
  pyproject.toml
Labels: bug

#64 feat: add autoflake and isort to pre-commit
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: enhancement

#59 feat: add cohere links to Streamlit app
  conversant/demo/streamlit_example.py
  conversant/demo/styles.css
Labels: enhancement

#66 test: remove lambda filter from parametrized get_current_prompt test
  tests/test_prompt_chatbot.py
Labels: tests

#67 docs: add vscode setup and PR naming guidelines
  CONTRIBUTORS.md
Labels: documentation

#70 docs: Update PyPI metadata and changelog for release of conversant v0.1.2
  CHANGELOG.md
  README.md
  pyproject.toml
Labels: documentation

#71 fix isort and black conflict
  .pre-commit-config.yaml
  CONTRIBUTORS.md
Labels: bug
